import necessary dependencies

In [2]:
import numpy as np

returns the sin of the argument in radians as type numpy.float64

In [3]:
def sin(x):
    return np.sin(x)

returns the cos of the argument in radians as type numpy.float64

In [4]:
def cos(x):
    return np.cos(x)

set dataTable to the entire tabulated list of sin(x) and cos(x) vs. x where x is tabulated between 0 and 2pi with a thousand entries

In [5]:
x = np.linspace(0, 2*np.pi, 1000)
sinx, cosx = sin(x), cos(x)
dataTable = np.transpose((sinx,cosx,x))

prints out the first 10 values of x, sin(x), and cos(x) in columns

In [6]:
for i in range(0,10):
    print(dataTable[i])

[0. 1. 0.]
[0.00628943 0.99998022 0.00628947]
[0.01257862 0.99992089 0.01257895]
[0.0188673  0.999822   0.01886842]
[0.02515525 0.99968356 0.0251579 ]
[0.03144219 0.99950557 0.03144737]
[0.03772789 0.99928805 0.03773685]
[0.0440121  0.999031   0.04402632]
[0.05029457 0.99873443 0.0503158 ]
[0.05657505 0.99839835 0.05660527]
